# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'CertificateAndKey.p12'
    certPwd: '$(P12password)'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'MovieViperProvisioningProfile.mobileprovision'
    removeProfile: false

- task: Xcode@5
  displayName: 'Build Project'
  inputs:
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    actions: 'build'
    scheme: 'GhibliViper'
    sdk: 'iphonesimulator'
    configuration: 'Debug'
    xcWorkspacePath: 'GhibliViper.xcworkspace'
    xcodeVersion: 'default'
